server:
  restart: always
  image: nginx:alpine
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
  links:
    - web:web
  ports:
    - "80:80"

web:
  restart: always
  build: ./app
  working_dir: /app
  volumes:
    - ./app:/app
  expose:
    - "8000"
  command: gunicorn -b 0.0.0.0:8000 app:app